AllCops:
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-minitest

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/StabbyLambdaParentheses:
  EnforcedStyle: require_no_parentheses

Style/Documentation:
  Enabled: false
