AllCops:
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-minitest

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/FormatStringToken:
  EnforcedStyle: template

Style/Documentation:
  Enabled: false
